# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=256M" "mode=755" ];
  };
#  fileSystems."/" =
#    {
#      device = "/dev/disk/by-uuid/ad115b46-8ee3-4119-bf43-4cc0f0053605";
#      fsType = "btrfs";
#      options = [ "subvol=nix/@" "noatime" "compress-force=zstd:1" "ssd" "discard=async" "space_cache=v2" ];
#    };
  fileSystems."/persistent" =
    {
      device = "/dev/disk/by-uuid/ad115b46-8ee3-4119-bf43-4cc0f0053605";
      fsType = "btrfs";
      options = [ "subvol=nix/@persistent" "noatime" "compress-force=zstd:1" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/AB2C-51DB";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/ad115b46-8ee3-4119-bf43-4cc0f0053605";
      fsType = "btrfs";
      options = [ "subvol=nix/@nix" "noatime" "compress-force=zstd:1" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/ad115b46-8ee3-4119-bf43-4cc0f0053605";
      fsType = "btrfs";
      options = [ "subvol=nix/@home" "noatime" "compress-force=zstd:1" "ssd" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    {
      device = "/dev/disk/by-uuid/ad115b46-8ee3-4119-bf43-4cc0f0053605";
      fsType = "btrfs";
      options = [ "subvol=nix/@log" "noatime" "compress-force=zstd:1" "ssd" "discard=async" "space_cache=v2" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
